export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_USER = "SET_USER";
export const SAVE_UID = "SAVE_UID";
export const PASSWORD_RESET_INITIATE = "PASSWORD_RESET_INITIATE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const POFILE_UPDATE_INIT = "POFILE_UPDATE_INIT";

export const POFILE_UPDATE_SUCCESS = "POFILE_UPDATE_SUCCESS";

export const POFILE_UPDATE_Fail = "POFILE_UPDATE_Fail";
export const PROFILE_PICTURE_UPLOAD_SUCCESS = "PROFILE_PICTURE_UPLOAD_SUCCESS";

export const JOB_POST_INIT = "JOB_POST_INIT";
export const JOB_POST_SUCCESS = "JOB_POST_SUCCESS"
export const JOB_POST_FAIL = "JOB_POST_FAIL"
export const GET_ALL_JOB_INIT = "GET_ALL_JOB_INIT"
export const GET_ALL_JOB_SUCCESS = "GET_ALL_JOB_SUCCESS"
