export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const SET_USER = "SET_USER";
export const SAVE_UID = "SAVE_UID";
export const PASSWORD_RESET_INITIATE = "PASSWORD_RESET_INITIATE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const STUDENT_POFILE_UPDATE_INIT = "STUDENT_POFILE_UPDATE_INIT";

export const STUDENT_POFILE_UPDATE_SUCCESS = "STUDENT_POFILE_UPDATE_SUCCESS";

export const STUDENT_POFILE_UPDATE_Fail = "STUDENT_POFILE_UPDATE_Fail";
export const PROFILE_PICTURE_UPLOAD_SUCCESS = "PROFILE_PICTURE_UPLOAD_SUCCESS";

export const CLEAR_ERROR = "CLEAR_ERROR";
